# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: GlobalSync.WorldClock
PackageVersion: 1.1.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://www.globalsync-ai.com/downloads/world-clock/windows/GlobalSync-World-Clock-1.1.0-Windows-Setup.exe
  InstallerSha256: D7DCBA15C6C25EE36813197DAF45148D8491E76E092DDBA7F6C5CCDE5E3EB3E2
  ProductCode: GlobalSync World Clock
  AppsAndFeaturesEntries:
  - DisplayName: GlobalSync World Clock
    Publisher: globalsync-ai
    DisplayVersion: 1.1.0
    ProductCode: GlobalSync World Clock
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.EdgeWebView2Runtime
ManifestType: installer
ManifestVersion: 1.12.0
